wso2/samples-apim

kubernetes-demo/README.md
kubernetes-demo/gce/gke_cluster/cluster_roles/gke/cluster_tasks/main.yml
kubernetes-demo/gce/gke_cluster/cluster_roles/gke/cluster_vars/main.yml
kubernetes-demo/gce/gke_cluster/cluster_site.yml
kubernetes-demo/ingress-deploy.sh
kubernetes-demo/ingress-undeploy.sh
kubernetes-demo/service-deploy.sh
kubernetes-demo/service-undeploy.sh

This PR automate WSO2 Deployment pattern 1 in Kubernetes.

Kubernetes demo  

---

README.md

Kubernetes demo

---

CustomJWTGenerator/README.md
CustomJWTGenerator/pom.xml
CustomJWTGenerator/src/main/java/org/wso2/carbon/test/CustomTokenGenerator.java
README.md

> This PR is to add a sample code for the custom JWT generation as explained here: https://docs.wso2.com/display/AM260/Passing+Enduser+Attributes+to+the+Backend+Using+JWT

Add the Custom JWT Generator Sample Code

---

CustomJWTGenerator/README.md

Updated as the sample was added in 3.0.0 as well. https://github.com/wso2/docs-apim/issues/34

Updated for 3.0.0

---

CustomJWTGenerator/pom.xml
CustomJWTGenerator/src/main/java/org/wso2/carbon/test/CustomClaimRetriever.java

add custom claim retriever

---

CustomGatewayJWTGenerator/README.md
CustomGatewayJWTGenerator/pom.xml
CustomGatewayJWTGenerator/src/main/java/org/wso2/carbon/test/CustomGatewayJWTGenerator.java

add custom gateway jwt Generator for 3.1.0

---

CustomJWTTransformer/LICENSE
CustomJWTTransformer/README.md
CustomJWTTransformer/pom.xml
CustomJWTTransformer/src/main/java/org/wso2/caron/test/CustomJWTTransformer.java
CustomJWTTransformer/src/main/java/org/wso2/caron/test/ExtendedJWTTransformer.java
CustomJWTTransformer/src/main/java/org/wso2/caron/test/internal/ActivatorComponent.java
CustomJWTTransformer/src/main/java/org/wso2/caron/test/internal/ServiceReferenceHolder.java
CustomJWTTransformer/src/main/resources/default-claim-mapping.properties

> Sample java code for the JWT Transformer

Add custom JWT Transformer

---

graphql-backend/README.md
graphql-backend/data/schema.js
graphql-backend/data/schema_graphql.graphql
graphql-backend/data/swapiSchema.js
graphql-backend/package-lock.json
graphql-backend/package.json
graphql-backend/server.js

This PR adds a sample Star Wars backend server which can be used to demonstrate the GraphQL scenarios in APIM.
Related issue: https://github.com/wso2/docs-apim/issues/1909

Add graphql sample backend

---

graphql-backend/.babelrc.json

This PR adds the missing .babelrc.json file to graphql sample backend.

Add missing files

---

streaming-api-backends/sse/README.md
streaming-api-backends/sse/pom.xml
streaming-api-backends/sse/src/main/java/sample/sse/server/Application.java
streaming-api-backends/sse/src/main/java/sample/sse/server/EventPublisher.java
streaming-api-backends/sse/src/main/java/sample/sse/server/MemoryInfo.java
streaming-api-backends/sse/src/main/java/sample/sse/server/ServerSentEventEmitter.java
streaming-api-backends/sse/src/main/resources/application.properties

Add sse server backend for streaming apis

---

streaming-api-backends/websocket-backend/README.md
streaming-api-backends/websocket-backend/index.js
streaming-api-backends/websocket-backend/package.json

> $subject. This server is used in the WebSocket tutorial.

[Streaming API] Add backend for WebSocket Streaming API

---

apim-tutorial/docker-compose.yml

Updated images

---

CustomGatewayJWTGenerator/pom.xml
CustomGatewayJWTGenerator/src/main/java/org/wso2/carbon/test/CustomGatewayJWTGenerator.java

fix samples for 4.0.0

---

graphql-backend/data/schema_graphql.graphql
graphql-backend/server.js

Related to doc samples for https://github.com/wso2/carbon-apimgt/pull/10895

add changes to sample graphql backend for subscriptions

---

analytics-event-publisher/README.md
analytics-event-publisher/src/main/java/org.wso2.am.analytics.publisher.sample.reporter/LogCounterMetric.java

This will update **analytics-event-publisher** sample to print a JSON formatted payload.
Related with - https://github.com/wso2-enterprise/choreo/issues/7428

Update Analytcs-Event-Publisher sample to print a JSON formatted payload

---

analytics-event-publisher/src/main/java/org.wso2.am.analytics.publisher.sample.reporter/LogCounterMetric.java

Change the log string as it can be used for the filter given in [ELK Analytics logstash filter config](https://apim.docs.wso2.com/en/latest/api-analytics/on-prem/elk-installation-guide/#installing-logstash).
Note: README.md file already has the sample log output for this change.

changed the log string as suitable for ELK analytics

---

apim-tutorial/resources/request.sh

Add script to invoke api

---

apim-tutorial/resources/coltrain-openapi.yaml

update backend EP

---

apim-tutorial/resources/Access_Control_Demo.postman_collection_v2.json

Update postman collection

---

apim-tutorial/dockerfiles/scripts/gogo-resources/deploy-api.sh
apim-tutorial/dockerfiles/scripts/quantis-resources/deploy-api.sh
apim-tutorial/dockerfiles/scripts/railco-resources/deploy-api.sh
apim-tutorial/dockerfiles/scripts/taxi-provider/TaxiProviderAPI.json

Fix syntax and version issues in sample script

---

apim-tutorial/resources/request.sh

Reduce wait time

---

apim-tutorial/dockerfiles/scripts/gogo-resources/notification/data.json
apim-tutorial/dockerfiles/scripts/gogo-resources/passengerinfo/data.json
apim-tutorial/dockerfiles/scripts/gogo-resources/passengerinfo/swagger.json
apim-tutorial/dockerfiles/scripts/quantis-resources/trainlocation/data.json

Fixing API names and descriptions

---

apim-tutorial/dockerfiles/scripts/railco-resources/employee/data.json
apim-tutorial/dockerfiles/scripts/railco-resources/employee/swagger.json
apim-tutorial/dockerfiles/scripts/taxi-provider/TaxiProviderAPI.json

Fixing names and descriptions in samples

---

analytics-custom-data-provider/README.md
analytics-custom-data-provider/pom.xml
analytics-custom-data-provider/src/main/java/org/wso2/carbon/apimgt/gateway/sample/publisher/CustomDataProvider.java

To guide folks to add custom analytics data to the existing event schema.
Example for: https://github.com/wso2/api-manager/issues/443
Follow the instructions provided in README

Add custom analytics data provider sample

---

analytics-custom-data-provider/pom.xml

To add license headers and fix typo

Adding license headers to pom

---

analytics-custom-data-provider/pom.xml

Add custom analytics data provider pom changes

---

analytics-custom-data-provider/README.md

[4.1.0] README changes

---

analytics-custom-data-provider/README.md

[4.0.0] README changes

---

analytics-custom-data-provider/README.md
analytics-custom-data-provider/pom.xml

To add support to building the sample locally and provide required guidance in README.

[4.0.0] Support building sample with local maven repository

---

analytics-custom-data-provider/README.md
analytics-custom-data-provider/pom.xml

To add support to building the sample locally and provide required guidance in README.

[4.1.0] Support building sample with local maven repository

---

analytics-custom-data-provider/README.md

To add README information changes.

[4.1.0] README for Analytics Custom Data Provider

---

api_governance_cli_tool/cli.js

add verbosity

---

api_governance_cli_tool/README.md

Improved the readme file by adding descriptive details about the `api.yaml` file and added more details about the API Governance  CLI tool.

Improved the README file of API Governance CLI Tool

---

apim-tutorial/backends/train-schedule/src/main/java/org/wso2/carbon/apimgt/tutorial/trainschedule/StationInformationControllerV2.java
apim-tutorial/backends/train-schedule/src/main/java/org/wso2/carbon/apimgt/tutorial/trainschedule/StationInformationManagerV2.java
apim-tutorial/backends/train-schedule/src/main/java/org/wso2/carbon/apimgt/tutorial/trainschedule/models/TrainV2.java

Add train info v2

---

apim-tutorial/backends/train-schedule/src/main/java/org/wso2/carbon/apimgt/tutorial/trainschedule/StationInformationControllerV2.java
apim-tutorial/backends/train-schedule/src/main/java/org/wso2/carbon/apimgt/tutorial/trainschedule/StationInformationManagerV2.java
apim-tutorial/backends/train-schedule/src/main/java/org/wso2/carbon/apimgt/tutorial/trainschedule/models/TrainV2.java
apim-tutorial/dockerfiles/scripts/tenant-creation.sh

> https://github.com/wso2/samples-apim/commit/02d1490eac25debc43626a29a7dc1d5bc013ccc3
> https://github.com/wso2/samples-apim/commit/455b43d84697efa94999c4c000a167c81eb61a7d

Update WSO2CON repository

---

api_governance_cli_tool/README.md
api_governance_cli_tool/cli.js

Fix the formatting changes of the `cli.js` file.

Fix formatting changes of cli.js file

---

thrift-analytics-data-provider/README.md
thrift-analytics-data-provider/pom.xml
thrift-analytics-data-provider/src/main/java/org/wso2/am/thrift/analytics/data/provider/ThriftAnalyticsDataProvider.java
thrift-analytics-publisher/README.md
thrift-analytics-publisher/pom.xml
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/Constants.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/EventQueue.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/InputValidator.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/ParallelQueueWorker.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/ThriftAnalyticsThreadFactory.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/ThriftClient.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/ThriftCounterMetric.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/ThriftMetricEventBuilder.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/ThriftMetricReporter.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/ThriftMetricSchema.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/ThriftStream.java

> $subject.
API Analytics events from WSO2 APIM 4.2.0 are published to the following Thrift streams:
- Request Events: `org.wso2.apimgt.statistics.request:4.2.0`
- Fault Events: `org.wso2.apimgt.statistics.fault:4.2.0`
- Throttle Events: `org.wso2.apimgt.statistics.throttle:4.2.0`
See the topic **Thrift stream Attributes** for the list of attributes of the above streams.
In WSO2 APIM 4.2.0, Some error events might be reported with `null` attributes (eg: `applicationConsumerKey` will be `null` when invoking an API with an invalid token), and fail during validation - since required attributes for the fault Thrift stream are null.
During such cases, the validation fails and these events are not reported. The error that is thrown during validation will NOT be logged by default - to avoid the …

Add Thrift Data Publisher & Data Provider

---

thrift-analytics-data-provider/pom.xml
thrift-analytics-publisher/pom.xml

Add carbon.apimgt import version range to the Thrift data provider & publisher

---

apim-tutorial/resources/apis/FinancialDataAPI/FinancialDataAPI.yaml

Add FinancialDataAPI OpenAPI definition

---

apim-tutorial/resources/apis/SalesForce/Salesforce.yaml

Add Salesforce API

---

apim-tutorial/resources/apis/HotelReservationAPI/HotelReservationAPI.json

Update hotel reservation API

---

thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/ThriftMetricEventBuilder.java

Setting apiResourceTemplate and apiMethod to default values

---

thrift-analytics-data-provider/src/main/java/org/wso2/am/thrift/analytics/data/provider/ThriftAnalyticsDataProvider.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/ThriftClient.java
thrift-analytics-publisher/src/main/java/org/wso2/am/thrift/analytics/publisher/ThriftMetricEventBuilder.java

Fix bugs to support WSO2 APIM Analytics Dashboard 3.2.0

Fix Thrift Data Provider and Publisher Bugs

---

custom-lambda-authorizer/README.md
custom-lambda-authorizer/index.mjs

Adds a sample lambda authorizer implementation

Adds a Custom Lambda Authorizer for AWS Gateway Federation

---

single-cp-multi-gw-tutorial/api-definitions/ComplianceReportAPI.json
single-cp-multi-gw-tutorial/api-definitions/HRSystemAPI.json
single-cp-multi-gw-tutorial/api-definitions/ProductCatalogAPI.json
single-cp-multi-gw-tutorial/apim-configs/acp-deployment.toml
single-cp-multi-gw-tutorial/apim-configs/gw-deployment.toml
single-cp-multi-gw-tutorial/apim-configs/tm-deployment.toml
single-cp-multi-gw-tutorial/sample-backends/compliance-api.js
single-cp-multi-gw-tutorial/sample-backends/hr-api.js
single-cp-multi-gw-tutorial/sample-backends/product-catalog-backend/Dockerfile
single-cp-multi-gw-tutorial/sample-backends/product-catalog-backend/deployment.yaml
single-cp-multi-gw-tutorial/sample-backends/product-catalog-backend/package.json
single-cp-multi-gw-tutorial/sample-backends/product-catalog-backend/server.js

Add resources for https://github.com/wso2-enterprise/wso2-apim-internal/issues/9722

Add single-cp to multi-gw resources

---

single-cp-multi-gw-tutorial/apim-configs/final-acp-deployment.toml

Add modified deployment.toml

---

single-cp-multi-gw-tutorial/api-definitions/ProductCatalogAPI.json
single-cp-multi-gw-tutorial/sample-backends/product-catalog-backend/deployment.yaml

Update k8s service URL

---

apim-tutorial/resources/apis/FinancialDataAPI/FinancialDataAPI.yaml

Update apim resource
